// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PFE.Infrastructure.Data;

#nullable disable

namespace PFE.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405215559_AddAnnouncements")]
    partial class AddAnnouncements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("PFE.Domain.Entities.AbsenceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasComment("Manager who will review this request");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("IX_AbsenceRequests_ManagerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AbsenceRequests_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AbsenceRequests_UserId");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("IX_AbsenceRequests_User_Date");

                    b.ToTable("AbsenceRequests");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_Name");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentChannelMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_ChannelMessages_DepartmentId");

                    b.HasIndex("SenderId");

                    b.ToTable("DepartmentChannelMessages");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentPoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowMultipleChoices")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("DepartmentPolls");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentPollOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("DepartmentPollOptions");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentPollVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<int>("PollOptionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PollOptionId");

                    b.HasIndex("UserId");

                    b.HasIndex("PollId", "UserId", "PollOptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_PollVotes_UniqueVote");

                    b.ToTable("DepartmentPollVotes");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Whether attendance is mandatory");

                    b.Property<bool>("RSVPEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Whether RSVP is enabled for this event");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasComment("Optional room where event takes place");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Events_CreatedByUserId");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("IX_Events_RoomId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Events_Type");

                    b.HasIndex("StartDateTime", "EndDateTime")
                        .HasDatabaseName("IX_Events_DateTimeRange");

                    b.ToTable("Events", t =>
                        {
                            t.HasCheckConstraint("CK_Events_EndDateTime_After_StartDateTime", "[EndDateTime] > [StartDateTime]");
                        });
                });

            modelBuilder.Entity("PFE.Domain.Entities.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResponseAt")
                        .HasColumnType("datetime2")
                        .HasComment("When user responded to the event invitation");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EventParticipants_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_EventParticipants_UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_EventParticipants_Event_User_Unique");

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("PFE.Domain.Entities.GeneralRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int")
                        .HasComment("User assigned to handle this request");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("IX_GeneralRequests_AssignedToUserId");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_GeneralRequests_Category");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_GeneralRequests_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_GeneralRequests_UserId");

                    b.ToTable("GeneralRequests");
                });

            modelBuilder.Entity("PFE.Domain.Entities.InternalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("UserId");

                    b.ToTable("InternalRequests");
                });

            modelBuilder.Entity("PFE.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ManagerComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedManagerId")
                        .HasDatabaseName("IX_LeaveRequests_AssignedManagerId");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("IX_LeaveRequests_ReviewedById");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LeaveRequests_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LeaveRequests_UserId");

                    b.HasIndex("UserId", "StartDate", "EndDate")
                        .HasDatabaseName("IX_LeaveRequests_User_DateRange");

                    b.ToTable("LeaveRequests", t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequests_EndDate_After_StartDate", "[EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("PFE.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Info");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Notifications_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notifications_UserId");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_Notifications_User_IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PFE.Domain.Entities.OfficeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50)
                        .HasComment("Table height in pixels/units");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PositionX")
                        .HasColumnType("int")
                        .HasComment("X coordinate in 2D layout");

                    b.Property<int>("PositionY")
                        .HasColumnType("int")
                        .HasComment("Y coordinate in 2D layout");

                    b.Property<int>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100)
                        .HasComment("Table width in pixels/units");

                    b.HasKey("Id");

                    b.ToTable("OfficeTables");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasComment("Maximum number of people");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Rooms_Name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Rooms_Type");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PFE.Domain.Entities.RoomReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("IX_RoomReservations_RoomId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RoomReservations_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RoomReservations_UserId");

                    b.HasIndex("RoomId", "StartDateTime", "EndDateTime")
                        .HasDatabaseName("IX_RoomReservations_Room_TimeRange");

                    b.ToTable("RoomReservations", t =>
                        {
                            t.HasCheckConstraint("CK_RoomReservations_EndDateTime_After_StartDateTime", "[EndDateTime] > [StartDateTime]");
                        });
                });

            modelBuilder.Entity("PFE.Domain.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Seat label/identifier (e.g., A1, B2)");

                    b.Property<int>("OfficeTableId")
                        .HasColumnType("int");

                    b.Property<int>("PositionX")
                        .HasColumnType("int")
                        .HasComment("X coordinate relative to table");

                    b.Property<int>("PositionY")
                        .HasColumnType("int")
                        .HasComment("Y coordinate relative to table");

                    b.HasKey("Id");

                    b.HasIndex("OfficeTableId")
                        .HasDatabaseName("IX_Seats_OfficeTableId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("PFE.Domain.Entities.SeatReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasComment("Reservation date (date only)");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_SeatReservations_Date");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SeatReservations_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SeatReservations_UserId");

                    b.HasIndex("SeatId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_SeatReservations_Seat_Date_Unique");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_SeatReservations_User_Date_Unique");

                    b.ToTable("SeatReservations");
                });

            modelBuilder.Entity("PFE.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LeaveBalance")
                        .HasColumnType("int")
                        .HasComment("Remaining leave days balance");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Users_DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Announcement", b =>
                {
                    b.HasOne("PFE.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PFE.Domain.Entities.AbsenceRequest", b =>
                {
                    b.HasOne("PFE.Domain.Entities.User", "Manager")
                        .WithMany("ManagedAbsenceRequests")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AbsenceRequests_Manager");

                    b.HasOne("PFE.Domain.Entities.User", "User")
                        .WithMany("AbsenceRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AbsenceRequests_User");

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentChannelMessage", b =>
                {
                    b.HasOne("PFE.Domain.Entities.Department", "Department")
                        .WithMany("ChannelMessages")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PFE.Domain.Entities.User", "Sender")
                        .WithMany("SentDepartmentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentPoll", b =>
                {
                    b.HasOne("PFE.Domain.Entities.DepartmentChannelMessage", "Message")
                        .WithOne("Poll")
                        .HasForeignKey("PFE.Domain.Entities.DepartmentPoll", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentPollOption", b =>
                {
                    b.HasOne("PFE.Domain.Entities.DepartmentPoll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentPollVote", b =>
                {
                    b.HasOne("PFE.Domain.Entities.DepartmentPoll", "Poll")
                        .WithMany("Votes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFE.Domain.Entities.DepartmentPollOption", "PollOption")
                        .WithMany("Votes")
                        .HasForeignKey("PollOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PFE.Domain.Entities.User", "User")
                        .WithMany("DepartmentPollVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poll");

                    b.Navigation("PollOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Event", b =>
                {
                    b.HasOne("PFE.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Events_CreatedByUser");

                    b.HasOne("PFE.Domain.Entities.Room", "Room")
                        .WithMany("Events")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Events_Room");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PFE.Domain.Entities.EventParticipant", b =>
                {
                    b.HasOne("PFE.Domain.Entities.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventParticipants_Event");

                    b.HasOne("PFE.Domain.Entities.User", "User")
                        .WithMany("EventParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventParticipants_User");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFE.Domain.Entities.GeneralRequest", b =>
                {
                    b.HasOne("PFE.Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("PFE.Domain.Entities.User", "AssignedToUser")
                        .WithMany("AssignedGeneralRequests")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_GeneralRequests_AssignedToUser");

                    b.HasOne("PFE.Domain.Entities.User", "User")
                        .WithMany("GeneralRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GeneralRequests_User");

                    b.Navigation("AssignedTo");

                    b.Navigation("AssignedToUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFE.Domain.Entities.InternalRequest", b =>
                {
                    b.HasOne("PFE.Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("PFE.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFE.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("PFE.Domain.Entities.User", "AssignedManager")
                        .WithMany("ManagedLeaveRequests")
                        .HasForeignKey("AssignedManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LeaveRequests_AssignedManager");

                    b.HasOne("PFE.Domain.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LeaveRequests_ReviewedBy");

                    b.HasOne("PFE.Domain.Entities.User", "User")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LeaveRequests_User");

                    b.Navigation("AssignedManager");

                    b.Navigation("ReviewedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Notification", b =>
                {
                    b.HasOne("PFE.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFE.Domain.Entities.RoomReservation", b =>
                {
                    b.HasOne("PFE.Domain.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("PFE.Domain.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoomReservations_Room");

                    b.HasOne("PFE.Domain.Entities.User", "User")
                        .WithMany("RoomReservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoomReservations_User");

                    b.Navigation("Manager");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Seat", b =>
                {
                    b.HasOne("PFE.Domain.Entities.OfficeTable", "OfficeTable")
                        .WithMany("Seats")
                        .HasForeignKey("OfficeTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Seats_OfficeTable");

                    b.Navigation("OfficeTable");
                });

            modelBuilder.Entity("PFE.Domain.Entities.SeatReservation", b =>
                {
                    b.HasOne("PFE.Domain.Entities.Seat", "Seat")
                        .WithMany("Reservations")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SeatReservations_Seat");

                    b.HasOne("PFE.Domain.Entities.User", "User")
                        .WithMany("SeatReservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SeatReservations_User");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFE.Domain.Entities.User", b =>
                {
                    b.HasOne("PFE.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Department", b =>
                {
                    b.Navigation("ChannelMessages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentChannelMessage", b =>
                {
                    b.Navigation("Poll");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentPoll", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("PFE.Domain.Entities.DepartmentPollOption", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PFE.Domain.Entities.OfficeTable", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Room", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("PFE.Domain.Entities.Seat", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("PFE.Domain.Entities.User", b =>
                {
                    b.Navigation("AbsenceRequests");

                    b.Navigation("AssignedGeneralRequests");

                    b.Navigation("CreatedEvents");

                    b.Navigation("DepartmentPollVotes");

                    b.Navigation("EventParticipants");

                    b.Navigation("GeneralRequests");

                    b.Navigation("LeaveRequests");

                    b.Navigation("ManagedAbsenceRequests");

                    b.Navigation("ManagedLeaveRequests");

                    b.Navigation("Notifications");

                    b.Navigation("RoomReservations");

                    b.Navigation("SeatReservations");

                    b.Navigation("SentDepartmentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
